pull_request_rules:
  - name: Automatic merge
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
      - check-success=lint_test_build
      - check-success="Semantic Pull Request"
      - check-success=license/cla
      - label=ready-to-merge
      - label!=do-not-merge
      - title~=^(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\([^)]+\))?:\s.+$
    actions:
      queue:
        method: squash
        name: default
  - name: Automatic head deletion
    conditions: []
    actions:
      delete_head_branch: {}

queue_rules:
  - name: default
    conditions:
      - check-success=lint_test_build
      - check-success="Semantic Pull Request"
